"""add not nullable to room name

Revision ID: 451bbe9a9e0b
Revises: cab83551c6f5
Create Date: 2024-06-13 12:24:33.572097

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '451bbe9a9e0b'
down_revision: Union[str, None] = 'cab83551c6f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'studios',
        'latitude',
        existing_type=sa.REAL(),
        type_=sa.Float(precision=8),
        existing_nullable=False,
    )
    op.alter_column(
        'studios',
        'longitude',
        existing_type=sa.REAL(),
        type_=sa.Float(precision=8),
        existing_nullable=False,
    )
    op.alter_column('rooms', 'name', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'studios',
        'longitude',
        existing_type=sa.Float(precision=8),
        type_=sa.REAL(),
        existing_nullable=False,
    )
    op.alter_column(
        'studios',
        'latitude',
        existing_type=sa.Float(precision=8),
        type_=sa.REAL(),
        existing_nullable=False,
    )
    op.alter_column('rooms', 'name', nullable=True)
    # ### end Alembic commands ###
