"""Url to string

Revision ID: 72dd7cfbd5fe
Revises: e91f59af6a80
Create Date: 2024-06-11 15:18:17.862329

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '72dd7cfbd5fe'
down_revision: Union[str, None] = 'e91f59af6a80'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'studios',
        'latitude',
        existing_type=sa.REAL(),
        type_=sa.Float(precision=8),
        existing_nullable=False,
    )
    op.alter_column(
        'studios',
        'longitude',
        existing_type=sa.REAL(),
        type_=sa.Float(precision=8),
        existing_nullable=False,
    )
    op.alter_column(
        'studios',
        'site_url',
        existing_type=sa.TEXT(),
        type_=sa.String(length=200),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'studios',
        'site_url',
        existing_type=sa.String(length=200),
        type_=sa.TEXT(),
        existing_nullable=True,
    )
    op.alter_column(
        'studios',
        'longitude',
        existing_type=sa.Float(precision=8),
        type_=sa.REAL(),
        existing_nullable=False,
    )
    op.alter_column(
        'studios',
        'latitude',
        existing_type=sa.Float(precision=8),
        type_=sa.REAL(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
