services:
  nginx:
    image: nginx:1.25.5
    container_name: nginx
    depends_on:
      - app
    ports:
      - "80:80"
    volumes:
      - ./static:/home/web/default/static
    configs: 
      - source: nginx-config
        target: /etc/nginx/conf.d/default.conf
        mode: 0444  # "только чтение" для всех
    deploy:
      restart_policy:
        condition: on-failure
      
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: app
    expose:
      - ${APP_PORT}
    depends_on:
      - db
    restart: always
    env_file:
      - .env
    deploy:
      restart_policy:
        condition: on-failure
      
  db:
    container_name: bbb_db
    image: postgres:16.2
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
      PGPORT: ${DB_PORT}
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    healthcheck:
      test: [ "CMD-SHELL", "sh -c 'pg_isready -U ${DB_USER} -d ${DB_NAME}'" ]
      interval: 5s
      timeout: 10s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - ${DB_PORT}
    env_file:
      - .env
      
volumes:
  postgres_data:
  
configs:
  nginx-config:
    file: ./nginx/nginx.conf 

