services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
      target: development
    ports:
      - ${APP_PORT}:${APP_PORT}
    env_file:
      - .env
    restart: on-failure
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:16.2
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
      PGPORT: ${DB_PORT}
    ports:
      - ${DB_PORT}:${DB_PORT}
    restart: on-failure
    healthcheck:
      test: [ "CMD-SHELL", "sh -c 'pg_isready -U ${DB_USER} -d ${DB_NAME}'" ]
      interval: 5s
      timeout: 10s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
