"""add email field to users

Revision ID: b71c309fc91a
Revises: e91f59af6a80
Create Date: 2024-05-18 16:25:31.102774

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b71c309fc91a'
down_revision: Union[str, None] = 'e91f59af6a80'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'studios',
        'latitude',
        existing_type=sa.REAL(),
        type_=sa.Float(precision=8),
        existing_nullable=False,
    )
    op.alter_column(
        'studios',
        'longitude',
        existing_type=sa.REAL(),
        type_=sa.Float(precision=8),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'studios',
        'longitude',
        existing_type=sa.Float(precision=8),
        type_=sa.REAL(),
        existing_nullable=False,
    )
    op.alter_column(
        'studios',
        'latitude',
        existing_type=sa.Float(precision=8),
        type_=sa.REAL(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
