"""add cascade delete

Revision ID: e311a95aa2ab
Revises: b198f50bc949
Create Date: 2024-06-16 19:08:01.942392

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'e311a95aa2ab'
down_revision: Union[str, None] = 'b198f50bc949'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('additional_services_room_id_fkey', 'additional_services', type_='foreignkey')
    op.create_foreign_key(None, 'additional_services', 'rooms', ['room_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('bookings_user_id_fkey', 'bookings', type_='foreignkey')
    op.drop_constraint('bookings_room_id_fkey', 'bookings', type_='foreignkey')
    op.create_foreign_key(None, 'bookings', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'bookings', 'rooms', ['room_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('employees_user_id_fkey', 'employees', type_='foreignkey')
    op.drop_constraint('employees_studio_id_fkey', 'employees', type_='foreignkey')
    op.create_foreign_key(None, 'employees', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'employees', 'studios', ['studio_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('reviews_room_id_fkey', 'reviews', type_='foreignkey')
    op.drop_constraint('reviews_studio_id_fkey', 'reviews', type_='foreignkey')
    op.drop_constraint('reviews_author_id_fkey', 'reviews', type_='foreignkey')
    op.create_foreign_key(None, 'reviews', 'users', ['author_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'reviews', 'rooms', ['room_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'reviews', 'studios', ['studio_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('rooms_studio_id_fkey', 'rooms', type_='foreignkey')
    op.create_foreign_key(None, 'rooms', 'studios', ['studio_id'], ['id'], ondelete='CASCADE')
    op.alter_column('studios', 'latitude',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=8),
               existing_nullable=False)
    op.alter_column('studios', 'longitude',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=8),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('studios', 'longitude',
               existing_type=sa.Float(precision=8),
               type_=sa.REAL(),
               existing_nullable=False)
    op.alter_column('studios', 'latitude',
               existing_type=sa.Float(precision=8),
               type_=sa.REAL(),
               existing_nullable=False)
    op.drop_constraint(None, 'rooms', type_='foreignkey')
    op.create_foreign_key('rooms_studio_id_fkey', 'rooms', 'studios', ['studio_id'], ['id'])
    op.drop_constraint(None, 'reviews', type_='foreignkey')
    op.drop_constraint(None, 'reviews', type_='foreignkey')
    op.drop_constraint(None, 'reviews', type_='foreignkey')
    op.create_foreign_key('reviews_author_id_fkey', 'reviews', 'users', ['author_id'], ['id'])
    op.create_foreign_key('reviews_studio_id_fkey', 'reviews', 'studios', ['studio_id'], ['id'])
    op.create_foreign_key('reviews_room_id_fkey', 'reviews', 'rooms', ['room_id'], ['id'])
    op.drop_constraint(None, 'employees', type_='foreignkey')
    op.drop_constraint(None, 'employees', type_='foreignkey')
    op.create_foreign_key('employees_studio_id_fkey', 'employees', 'studios', ['studio_id'], ['id'])
    op.create_foreign_key('employees_user_id_fkey', 'employees', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'bookings', type_='foreignkey')
    op.drop_constraint(None, 'bookings', type_='foreignkey')
    op.create_foreign_key('bookings_room_id_fkey', 'bookings', 'rooms', ['room_id'], ['id'])
    op.create_foreign_key('bookings_user_id_fkey', 'bookings', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'additional_services', type_='foreignkey')
    op.create_foreign_key('additional_services_room_id_fkey', 'additional_services', 'rooms', ['room_id'], ['id'])
    # ### end Alembic commands ###
